name: build and test senaite.core
on:
  - push
  - pull_request
env:
  PLONE_VERSION: "5.2"
jobs:
  build-and-test:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v3
      # Taken from https://github.com/xenserver-next/python-libs/blob/master/.github/workflows/main.yml
      - name: Setup Python 2.7.18
        # uses: actions/setup-python@v4 due to https://github.com/actions/setup-python/issues/672:
        # https://github.com/MatteoH2O1999/setup-python
        # This action tries to build from source all Python versions that actions/setup-python
        # does not support. It also allows to cache built versions so that after the first run,
        # installation time is really low. Hope it works also with 20.04, else it needs more changes:
        uses: MatteoH2O1999/setup-python@v1
        with:
          python-version: 2.7.18
          allow-build: info
          cache-build: true
          cache: pip
      - name: cache eggs
        uses: actions/cache@v3
        with:
          key: eggs-cache-${{ hashFiles('buildout.cfg', 'requirements.txt') }}
          path: |
            eggs/
      - name: install
        run: |
          pip install virtualenv
          virtualenv -p `which python` .
          bin/pip install -r requirements.txt
          bin/buildout -N -t 3 annotate
          bin/buildout -N -t 3
      - name: lint
        run: |
          bin/pip install flake8
          bin/flake8 --config ci_flake8.cfg src/{bika,senaite}/
      - name: test
        run: |
          bin/test -s senaite.core.tests
